name: nameof_modern
description: An upgrade modern code of the official and original nameof. Nameof package, that is Generator for  Dart class member's names, such as fields etc...
version: 0.0.2
homepage: https://www.elssiany.com/
repository: https://github.com/elssiany/nameof_modern
issue_tracker: https://github.com/elssiany/nameof_modern/issues

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  build: ^2.4.1
  source_gen: ^1.5.0
  build_config: ^1.1.1
  nameof_annotation_modern: ^0.0.3

dev_dependencies:
  build_runner: ^2.4.9
  build_test: ^2.2.2
  source_gen_test: ^1.0.6
  lints: ^3.0.0
  test: ^1.25.4
