name: example
description: Example for Nameof Annotation Modern package
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  nameof_annotation_modern: ^0.0.1

dev_dependencies:
  lints: ^3.0.0